### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by smsaladi** [parkin/parkin.github.io#1]
but is this the right way to congratulate you on becoming a doctor?

**Comment by smsaladi** [comment]
it was either here or [parkin/CU-Bus-Guide](https://github.com/parkin/CU-Bus-Guide) since i cant find your email anymore.

(but really congrats)

**Comment by parkin** [comment]
haha thanks! Closing this issue is definitely the best way to celebrate defending. I hope you are doing well @smsaladi!
